<?php

namespace Battis\Calendar\iCalendar\RFC5545\Properties\Recurrence;

use Battis\Calendar\iCalendar\RFC5545\Properties\DefaultDateTimeProperty;

/**
Exception Date-Times Property

{@link https://tools.ietf.org/rfcmarkup/5545#section-3.8 RFC 5545 &sect;3.8}
```RFC
The following properties can appear within calendar components, as
specified by each component property definition.
```

{@link https://tools.ietf.org/rfcmarkup/5545#section-3.8.5 RFC 5545 &sect;3.8.5}
```RFC
The following properties specify recurrence information in calendar
components.
```

{@link https://tools.ietf.org/rfcmarkup/5545#section-3.8.5.1 RFC 5545 &sect;3.8.5.1}
```RFC
Purpose:  This property defines the list of DATE-TIME exceptions for
	 recurring events, to-dos, journal entries, or time zone
	 definitions.
```
```RFC
Description:  The exception dates, if specified, are used in
	 computing the recurrence set.  The recurrence set is the complete
	 set of recurrence instances for a calendar component.  The
	 recurrence set is generated by considering the initial "DTSTART"
	 property along with the "RRULE", "RDATE", and "EXDATE" properties
	 contained within the recurring component.  The "DTSTART" property
	 defines the first instance in the recurrence set.  The "DTSTART"
	 property value SHOULD match the pattern of the recurrence rule, if
	 specified.  The recurrence set generated with a "DTSTART" property
	 value that doesn't match the pattern of the rule is undefined.
	 The final recurrence set is generated by gathering all of the
	 start DATE-TIME values generated by any of the specified "RRULE"
	 and "RDATE" properties, and then excluding any start DATE-TIME
	 values specified by "EXDATE" properties.  This implies that start
	 DATE-TIME values specified by "EXDATE" properties take precedence
	 over those specified by inclusion properties (i.e., "RDATE" and
	 "RRULE").  When duplicate instances are generated by the "RRULE"
	 and "RDATE" properties, only one recurrence is considered.
	 Duplicate instances are ignored.

	 The "EXDATE" property can be used to exclude the value specified
	 in "DTSTART".  However, in such cases, the original "DTSTART" date
	 MUST still be maintained by the calendaring and scheduling system
	 because the original "DTSTART" value has inherent usage
	 dependencies by other properties such as the "RECURRENCE-ID".
```
*/
class ExceptionDateTimes extends DefaultDateTimeProperty {

	protected $name = 'EXDATE';
}
